env:
  global:
    - Features=use-mock-routing
    - RUST_BACKTRACE=1
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
sudo: false
branches:
  only:
    - master
    - dev
cache:
  cargo: true
script:
  - if [[ $TRAVIS_RUST_VERSION = stable ]]; then
      cargo test --release --no-run
      cargo test --release --features use-mock-routing
    fi
after_script:
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/run_clippy.sh
  - . run_clippy.sh
